Pull Request - Index
garett09/afk-hotel pull request #2
Opened 2021-05-13 14:41 UTC by Stateria

2021-05-13 14:44 UTC, eduardonacion approved these changes
NICE COCK

2021-05-14 00:36 UTC, garett09 commented
Improve the code.

2021-05-14 00:36 UTC, garett09 commented
Reopen: check some issues and remove some unnecessary codes

2021-05-14 01:36 UTC, garett09 commented on css/sample.css
> -/**
Do not delete: this is for sample

2021-05-14 01:36 UTC, garett09 commented on index.html
> +     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossori
fix formatting

2021-05-14 01:36 UTC, garett09 commented on index.html
> +<!-- Bootstrap LINKS -->
fix formatting

2021-05-14 01:45 UTC, garett09 requested changes
Kindle check the commits #2 

- [ check index.html] 
@Stateria

2021-05-14 01:45 UTC, garett09 commented on index.html
> +     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossori
```suggestion
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
```
Kindly review to this 
<link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
      crossorigin="anonymous"
    />

2021-05-14 01:45 UTC, garett09 commented on index.html
> +	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></s
Kindly copy the same formatting as line 10.

2021-05-14 01:45 UTC, garett09 commented on js/sample.js
> -/**
Do note remove### #

2021-05-14 07:21 UTC, garett09 approved these changes
Medyo deliks lang yung line 10 ng index.php. Will take note kapag nag deploy kung gumana. elsem edit ko nalang

2021-05-14 07:26 UTC, closed without merging